### PR TITLE
Resolved: "// TODO: flush after every 32kb instead of every file to r…

### PR DESCRIPTION
**Pull request by jtrinh27**
flush after every 32kb instead of every file to reduce memory

### CODE REVIEW

**Comment by skrivy** [comment]
@scosman Could you please get this merged? Thank you

**Comment by almogtavor** [comment]
@skrivy this project is inactive for 2 years now. You can check out my fork in [bundle-streamer](https://github.com/almogtavor/bundle-streamer). My project includes the flushing feature as well as other features like `tar` support, public image etc

**Comment by scosman** [comment]
io.Copy apparently already does use a 32KB buffer (strange it's the exact amount from my comment, but I'll take it).

Closing since this is not needed. I'll clean up the comment.

https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/io/io.go;l=385

**Comment by scosman** [comment]
I may still do a progressive flush version of this... But I want to work on the inbound request memory usage in the same change.

**Pull request closed without merging**
